name: nft-backend

on:
  push:
    branches:
      - 'main'

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: bitnami/postgresql:latest
        env:
          POSTGRES_USER: ${{secrets.POSTGRES_USER}}
          POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
          POSTGRES_DB: ${{secrets.POSTGRES_DB}}
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U test_user"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Configure node
        id: configure-node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        id: install-pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Install dependencies
        id: install-dependencies
        run: |
          pnpm install

      - name: Run Unit Test
        id: run-unit-test
        run: pnpm test:cov

      - name: Run e2e Test
        id: run-e2e-test
        run: |
          echo "DATABASE_URL=postgresql://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@localhost:5432/${{ vars.DATABASE_DB_NAME }}?schema=public" >> $GITHUB_ENV
          echo "POSTGRES_USER=${{secrets.POSTGRES_USER}} >> $GITHUB_ENV"
          echo "POSTGRES_PASSWORD=${{secrets.POSTGRES_PASSWORD}} >> $GITHUB_ENV"
          echo "POSTGRES_DB=${{secrets.POSTGRES_DB}} >> $GITHUB_ENV"
          pnpm test:e2e
